import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '@/styles/Home.module.css'

import React, { useMemo } from 'react';

import { useLoadScript, GoogleMap, MarkerF, CircleF } from '@react-google-maps/api';

import type { NextPage } from 'next';
import PlacesAutocomplete from '../components/PlacesAutocomplete';

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  
  const libraries = useMemo(() => ['places'], []);

  const mapCenter = useMemo(() => ({
      lat: 39.909484,
      lng: 32.867518
  }), []);

  const mapOptions = useMemo<google.maps.MapOptions>(() => ({
    disableDefaultUI: true,
    clickableIcons: true,
    scrollwheel: false,
  }), []);
  
  const { isLoaded } = useLoadScript({
    googleMapsApiKey: process.env.NEXT_PUBLIC_GOOGLE_MAPS_KEY as string,
    libraries: libraries as any
  });

  if (!isLoaded) {
    return <p>loading..</p>
  }
  return (
    <>
      <Head>
        <title>Map Project</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/icons8-curved-arrow-16.png" />
      </Head>
      <main 
      className={styles.main}
      >
        <div className={styles.container}>
          <div className={styles.leftColumn}>
            <PlacesAutocomplete />
        </div>
          <div className={styles.rightColumn}>
            <GoogleMap 
              options={mapOptions}
              zoom={15}
              center={mapCenter}
              mapTypeId={google.maps.MapTypeId.ROADMAP}
              mapContainerStyle={{ width: '800px', height: '600px' }}
              onLoad={() => console.log('Map Component Loaded...')}
            >
              {/* {[1000, 2500].map((radius, idx) => {
                return (
                  <CircleF
                    key={idx}
                    center={mapCenter}
                    radius={radius}
                    onLoad={() => console.log('Circle Load..')}
                    options={{
                      fillColor: radius > 1000 ? 'red' : 'green',
                      strokeColor: radius > 1000 ? 'red' : 'green',
                      strokeOpacity: 0.8,
                    }}
                  />
                )
              })
                } */}
              <MarkerF
                position={mapCenter}
                onLoad={() => console.log('Marker Loaded')}
                icon="/icons8-curved-arrow-32.png"
              />
            </GoogleMap>
          </div>
        </div>


      </main>
    </>
  )
}
